### PR TITLE
Issue #4 Enhancement - Limit to 5 Guesses

### PR DESCRIPTION
**Pull request by joshuasachtleben**
This enhancement introduces the functionality of limiting a player to 5 guesses.  The player will accrue a score for each correct answer.  When a question loads, the user will have 5 guesses to get the answer correct.  For each incorrect error, the response will display "Incorrect" and display the number of remaining guesses available to the player.  Upon submitting 5 incorrect guesses for one question, the response will be "GAME OVER", and the player will be displayed their final score.  The player can then select the "Restart" button to restart the game.  Upon restarting the game, the score goes back to 0, and a new question is loaded.

### CODE REVIEW

**Comment by robrich502** [comment]
Looks good!  I am going to have to manually merge this, as there are some conflicts.

**Comment by robrich502** [comment]
On another note.. We actually made this same feature in class last weds but I never commited it to the project.. hehe.  Yours is a bit nicer tho!

**Comment by joshuasachtleben** [comment]
Nice!  I'm just glad it's useful.

**Comment by joshuasachtleben** [comment]
Enhancement has been merged with other changes made to project.  It seems that some recent changes to nav menu and footer content have not been styled and are being displayed in an undesired format.  Another issue is going to need to be logged to have someone address this.

**Comment by robrich502** [comment]
Hmmm it must have been erin's pull request that I just merged... I can revert it, if it's not rendering properly.

**Comment by robrich502** [comment]
I'll just merge it and we can fix it later.

**Pull request merged**
