### PR TITLE
Removed bootstrap and made mobile friendly, also added copyright line to couple pages where it was removed

### PR DESCRIPTION
**Pull request by JavidCode**

### CODE REVIEW

**Comment by JavidCode** [comment]
New changes made incorporating commit made earlier this morning.  Added banner logo and code louisville logo in footer linking to code louisville website.

**Comment by JavidCode** [comment]
Added social buttons for sharing from wordgame.html page.

**Comment by JavidCode** [comment]
Small changes

**Comment by robrich502** [comment]
pull request has been manually merged.

**Comment by JavidCode** [comment]
@robrich22 There are other commits above copyright line that need to be in place for footer to stick to bottom and be centered.  The style.css needs to be refreshed for the changes to reflect correctly.  I also added some social media sharing that I don't see.

**Pull request closed without merging**
