### PR TITLE
updated Style.css page height and added bracket

### PR DESCRIPTION
**Pull request by JavidCode**

### CODE REVIEW

**Comment by robrich22** [comment]
We are going to have to figure out how to fix your local repo.  This pull request has all the same commits as last, plus an extra one...

**Comment by robrich22** [comment]
I'v already merged alot of this.

**Comment by JavidCode** [comment]
I've deleted my repo and starting from scratch.

**Comment by JavidCode** [comment]
Hopefully all my commits are gone and we can from there.

**Comment by JavidCode** [comment]
Do you see other commits from me after this one?

**Pull request closed without merging**
